### ISSUE TITLE
does 3DFT support schedule animation export

### ISSUE THREAD

**Issue by Dom24123** [iTwin/unreal-engine-3dft-plugin#22]
i have an itwin with schedule linked and exported form Synchro. in the limitations section of the repository it states that schedule animation is not possible however in the showcase video it clearly showcase that schedule animation is possible for 4D animations of construction. Can this please be confirmed?

**Comment by danieliborra** [comment]
Exactly, the documentation is correct, schedule animation **is not supported.**

The video you're referring to is a presentation we did at the Unreal Fest 2022 to talk about 3DFT technology and some projects based on that technology. There was a demo that included schedule animation, which was done modifying this plugin, but not using this plugin as is.
Since this plugin is open source, you can modify it for many use cases like animation, simulation, etc. wherever your imagination and UE5 can take you :)

Please, be aware that this project is a Technical Preview and is available for testing purposes only, and not to be used in production.

**Comment by Dom24123** [comment]
Thanks for response Daniel, any luck or literature on how to modify the plugin to support schedule animation. As of now i have been using itwin data smith export to be able to play schedule animation in unreal engine.

**Comment by danieliborra** [comment]
I'd start by looking for how to export and read Synchro animations. Then, check the plugin's code to see which parts are generating the dynamic meshes that Unreal render, and modify its visibility e.g. using a lookup texture that changes according to the schedule.

**Comment by danieliborra** [comment]
Thanks to you!
